### PR TITLE
Minidnf use unload plugins

### PR DESCRIPTION
**Pull request by didib**

### CODE REVIEW

**Comment by didib** [comment]
Rebased

**Comment by didib** [comment]
Checked the resulting otopi_logs - all of them still have only '_plugins._unload', dnf patch probably still not included in el9.

**Comment by didib** [comment]
Tested manually on CentOS Stream 9 with dnf-4.14.0-3.el9.noarch that now includes unload_plugins. Looks ok, merging.

Solves #40.

**Review by sandrobonazzola — APPROVED** [review]
LGTM

**Pull request merged**
