### PR TITLE
github: Show git log

### PR DESCRIPTION
**Pull request by didib**
Change-Id: Id4615915f12fb5abd4822b211da5a37d0800c700
Signed-off-by: Yedidyah Bar David <didi@redhat.com>

### CODE REVIEW

**Review by sandrobonazzola — APPROVED** [review]
LGTM

**Comment by didib** [comment]
Context: https://lists.ovirt.org/archives/list/devel@ovirt.org/thread/7SEFKOASOATTMO2NK2SBWMOV4CV6LZOS/

**Review by sandrobonazzola — APPROVED** [review]
LGTM

**Comment by didib** [comment]
I prefer #25, closing.

**Pull request closed without merging**
